import type { DCXRole, DCXTrinityResult, DCXContext } from './ingest.types';
import { DCX_MODELS, buildDCXPrompt } from './dcx.prompts';

interface OllamaResponse {
  model: string;
  message?: { content: string };
  response?: string;
  done: boolean;
}

/**
 * DCX Trinity Engine — Mind → Soul → Body pipeline via Ollama.
 *
 * Each role runs sequentially so downstream roles see upstream output.
 * Falls back gracefully if Ollama is unavailable.
 */
export class DCXTrinity {
  private baseUrl: string;

  constructor(ollamaBaseUrl?: string) {
    this.baseUrl = ollamaBaseUrl ?? process.env.OLLAMA_BASE_URL ?? 'http://localhost:11434';
  }

  /** Run the full Mind → Soul → Body pipeline */
  async run(context: DCXContext): Promise<DCXTrinityResult> {
    const start = Date.now();

    // Mind first
    const mindOutput = await this.callRole('mind', context);

    // Soul receives Mind's analysis as additional context
    const soulContext: DCXContext = {
      ...context,
      signals: [...context.signals, `[DCX-Mind Analysis]: ${mindOutput.substring(0, 500)}`],
    };
    const soulOutput = await this.callRole('soul', soulContext);

    // Body receives both Mind and Soul
    const bodyContext: DCXContext = {
      ...context,
      signals: [
        ...context.signals,
        `[DCX-Mind Analysis]: ${mindOutput.substring(0, 500)}`,
        `[DCX-Soul Assessment]: ${soulOutput.substring(0, 500)}`,
      ],
    };
    const bodyOutput = await this.callRole('body', bodyContext);

    // Synthesize
    const synthesized = this.synthesize(mindOutput, soulOutput, bodyOutput, context);

    return {
      mind: mindOutput,
      soul: soulOutput,
      body: bodyOutput,
      synthesized,
      latencyMs: Date.now() - start,
    };
  }

  /** Call a single DCX role via Ollama */
  private async callRole(role: DCXRole, context: DCXContext): Promise<string> {
    const config = DCX_MODELS[role];
    const userPrompt = buildDCXPrompt(role, context);

    try {
      const res = await fetch(`${this.baseUrl}/api/chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: config.model,
          messages: [
            { role: 'system', content: config.systemPrompt },
            { role: 'user', content: userPrompt },
          ],
          stream: false,
          options: {
            temperature: config.temperature,
            num_predict: config.maxTokens,
          },
        }),
        signal: AbortSignal.timeout(120_000),
      });

      if (!res.ok) {
        throw new Error(`Ollama ${res.status}: ${await res.text()}`);
      }

      const data = (await res.json()) as OllamaResponse;
      return data.message?.content ?? data.response ?? `[${role}] No response`;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`DCX-${role} error:`, msg);
      return `[${role}] Unavailable: ${msg}`;
    }
  }

  /** Synthesize the three outputs into a unified report */
  private synthesize(
    mind: string,
    soul: string,
    body: string,
    context: DCXContext
  ): string {
    const lines: string[] = [
      `# DCX Trinity Report${context.corridorId ? ` — ${context.corridorId}` : ''}`,
      '',
      '## 🧠 Mind (Analytical)',
      mind.substring(0, 1000),
      '',
      '## 💫 Soul (Humanitarian)',
      soul.substring(0, 1000),
      '',
      '## ⚡ Body (Operational)',
      body.substring(0, 1000),
      '',
      '---',
      `*Generated by DCX Trinity at ${new Date().toISOString()}*`,
      `*Signals processed: ${context.signals.length}*`,
    ];

    return lines.join('\n');
  }

  /** Health check — verify Ollama is reachable and models are available */
  async healthCheck(): Promise<{
    reachable: boolean;
    models: string[];
    missing: string[];
  }> {
    try {
      const res = await fetch(`${this.baseUrl}/api/tags`, {
        signal: AbortSignal.timeout(5_000),
      });
      if (!res.ok) return { reachable: false, models: [], missing: [] };

      const data = (await res.json()) as { models?: Array<{ name: string }> };
      const available = (data.models ?? []).map((m) => m.name);
      const required = Object.values(DCX_MODELS).map((c) => c.model);
      const missing = required.filter((r) => !available.some((a) => a.startsWith(r.replace(':latest', ''))));

      return { reachable: true, models: available, missing };
    } catch {
      return { reachable: false, models: [], missing: [] };
    }
  }
}
